version: "3.8"

services:
  nextjs:
    container_name: nextjs_app
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules # Éviter d'écraser node_modules
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/testapp
    command: ["npm", "run", "dev"]
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=testapp

volumes:
  nextjs_volume:
  mongodb_data:
